name: Deploy to GCP (Static way)

on:
  push:
    branches:
      - main

permissions:
  contents: 'read'
  id-token: 'write' # Habilitar el token de OIDC

env:
  PROJECT_ID: luma-idp
  BUCKET_NAME: nttdata-store-demo

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: 'Authenticate to GCP'
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/476678501255/locations/global/workloadIdentityPools/github-demo-pool/providers/github-demo-provider'
          service_account: 'github-actions-deployer@luma-idp.iam.gserviceaccount.com'

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Delete existing files in GCS bucket
        run: |
          gsutil -m rm -r gs://${{ env.BUCKET_NAME }}/* || true

      - name: Upload static files to GCS bucket
        run: |
          gsutil -m rsync -r app/src gs://${{ env.BUCKET_NAME }}